spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/solitary
    driverClassName: org.postgresql.Driver
    username: hukabo
    password: hukabo
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect