spring:
  datasource:
#    url: jdbc:postgresql://solitary.cbeueuqs0ksx.ap-northeast-2.rds.amazonaws.com/solitary
    url: jdbc:postgresql://localhost/solitary
    driverClassName: org.postgresql.Driver
#    username: hukabo95
#    password: hukabo95
    username: hukabo
    password: hukabo
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect